jobs/urls.py
from django.conf.urls import url

from jobs import views

app_name = "jobs"

urlpatterns = [
    url(r'^$', views.index, name='index'),
	url(r'^add/$', views.add, name='add'),
	url(r'^add/submit/$', views.addsubmit, name='addsubmit'),
	url(r'^show/(?P<job_id>[0-9]+)/$', views.show, name='show'),
    url(r'^remove/(?P<job_id>[0-9]+)/$', views.remove, name='remove')
]

meetings/urls.py
from django.conf.urls import url

from meetings import views

app_name = "meetings"

urlpatterns = [
    url(r'^$', views.index, name='index'),
	url(r'^add/$', views.add, name='add'),
	url(r'^add/submit/$', views.addsubmit, name='addsubmit'),
	url(r'^show/(?P<meeting_id>[0-9]+)/$', views.show, name='show'),
    url(r'^remove/(?P<meeting_id>[0-9]+)/$', views.remove, name='remove')
]

organizer/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

from organizer import settings
from organizer import views

from organizer.tools import IsLinux

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^jobs/', include('jobs.urls')),
    url(r'^meetings/', include('meetings.urls')),
    url(r'^accounts/login/$', views.account_login, name='login'),
    url(r'^accounts/logged_in/$', views.account_logged_in, name='logged_in'),
    url(r'^accounts/logout/$', views.account_logout, name='logout'),
    url(r'^accounts/logged_out/$', views.account_logged_out, name='logged_out'),
    url(r'^accounts/create/$', views.account_create, name='create'),
    url(r'^accounts/created/$', views.account_created, name='created'),
    url(r'^admin/', admin.site.urls),
]

if not IsLinux():
    favicon_view = RedirectView.as_view(url=settings.STATIC_URL + 'favicon.ico')
    robots_view = RedirectView.as_view(url=settings.STATIC_URL + 'robots.txt')
    urlpatterns.append(url(r'^favicon\.ico$', favicon_view))
    urlpatterns.append(url(r'^robots\.txt$', robots_view))

meetings/models.py
from __future__ import unicode_literals

from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.dateformat import DateFormat
from django.utils.formats import get_format

@python_2_unicode_compatible
class Meeting(models.Model):
    user = models.ForeignKey(User)
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=1000, blank=True, null=True)
    begin = models.DateTimeField()
    end = models.DateTimeField()
    added = models.DateTimeField(default=timezone.now)
    send_email = models.BooleanField(default=False)
    email_date = models.DateTimeField(blank=True, null=True)
    email_was_send = models.BooleanField(default=False, blank=True)

    def __str__(self):
        fixed_date = timezone.make_naive(self.begin)
        datestr = DateFormat(fixed_date).format(get_format('DATE_FORMAT'))
        return "%s [%s]" % (self.title, datestr)

meetings/views.py
# coding: utf-8

from django.shortcuts import render
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from .models import Meeting
from organizer.tools import ErrorMessage, IsNullOrEmpty, HtmlDateParse

@login_required
def index(request):
    meetings = Meeting.objects.filter(user=request.user)
    context = { 'meetings': meetings }
    return render(request, 'meetings/index.html', context)

@login_required
def add(request):
    return render(request, 'meetings/add.html')

@login_required
def addsubmit(request):
    error = ErrorMessage()

    title = request.POST.get("title")
    description = request.POST.get("description")
    begin = request.POST.get("begin")
    end = request.POST.get("end")
    send_email = request.POST.get("send_email") == "on"
    email_date = request.POST.get("email_date")

    #print("begin: '{}', end: '{}'".format(begin, end))

    if IsNullOrEmpty(title):
        error.set("Musisz podać tytuł spotkania!")
    elif IsNullOrEmpty(begin) or IsNullOrEmpty(end):
        error.set("Musisz podać datę spotkania!")
    elif send_email and IsNullOrEmpty(email_date):
        error.set("Musisz podać datę emaila!")

    if error.good() and description is not None:
        description = description.strip()

    if error.good():
        date_from = HtmlDateParse(begin)
        date_to = HtmlDateParse(end)
        if date_from is None or date_to is None:
            error.set("Data spotkania jest nieprawidłowa!")
        elif date_from <= timezone.now():
            error.set("Data spotkania musi wyprzedzać aktualny czas!")
        elif date_to < date_from:
            error.set("Przedział czasowy spotkania jest nieprawidłowy!")

    if error.good() and send_email:
        email_date = HtmlDateParse(email_date)
        if email_date is None:
            error.set("Data emaila jest nieprawidłowa!")
        elif email_date <= timezone.now():
            error.set("Data emaila musi wyprzedzać aktualny czas!")
        elif email_date > date_from:
            error.set("Data emaila musi poprzedzać datę spotkania!")

    context = {'error': str(error)}

    if error.good():
        meeting = Meeting()
        meeting.user = request.user
        meeting.title = title
        meeting.description = (description if len(description) > 0 else None)
        meeting.begin = date_from
        meeting.end = date_to
        meeting.send_email = send_email
        meeting.email_date = (email_date if send_email else None)
        meeting.email_was_send = False
        meeting.save()

        context.update({'meeting': meeting})

    return render(request, 'meetings/addsubmit.html', context)

@login_required
def show(request, meeting_id):
    error = ErrorMessage()

    try:
        meeting = Meeting.objects.get(id=meeting_id)
    except:
        error.set("Spotkanie o podanym ID nie istnieje!")
    else:
        if meeting.user != request.user:
            error.set("Nie jesteś właścicielem tego spotkania!")

    context = {'error': str(error)}

    if error.good():
        context.update({'meeting': meeting})

    return render(request, 'meetings/show.html', context)

@login_required
def remove(request, meeting_id):
    error = ErrorMessage()

    try:
        meeting = Meeting.objects.get(id=meeting_id)
    except:
        error.set("Spotkanie o podanym ID nie istnieje!")
    else:
        if meeting.user != request.user:
            error.set("Nie jesteś właścicielem tego spotkania!")

    if error.good():
        meeting.delete()

    context = {'error': str(error)}

    return render(request, 'meetings/remove.html', context)

templates/meetings/add.html
{% extends 'meetings/base.html' %}

{% block content-title %}Tworzenie spotkania{% endblock %}

{% block content %}
	<script type="text/javascript">
	    var sendEmailCheckBox = 'input[name=send_email]'
	    var emailDateInput = 'input[name=email_date]'
	    var emailDateBlock = '#email_date_block'
	    var datePickerBegin = '#datetimepicker1'
	    var datePickerEnd = '#datetimepicker2'
	    var datePickerEmail = '#datetimepicker3'

		function onSendEmailChange() {
		    if ($(sendEmailCheckBox).is(":checked")) {
		    	$(emailDateBlock).stop().fadeIn(500);
		    	$(emailDateInput).attr('required', "required");
		    } else {
	    		$(emailDateBlock).stop().fadeOut(500);
		    	$(emailDateInput).removeAttr('required');
            }
		}
		
		function getCurrentDate() { return moment(new Date()); }
		function getBeginDate() { return $(datePickerBegin).data("DateTimePicker").date(); }
		function getEndDate() { return $(datePickerEnd).data("DateTimePicker").date(); }
		function getEmailDate() { return $(datePickerEmail).data("DateTimePicker").date(); }

		function checkDatesAreValid() {
		    var beginDate = getBeginDate();
		    var endDate = getEndDate();
		    if (beginDate == null && endDate == null) {
		        $(datePickerBegin).removeClass('has-warning has-error has-success');
		        $(datePickerEnd).removeClass('has-warning has-error has-success');
		    } else if (beginDate == null && endDate != null) {
		        $(datePickerBegin).removeClass('has-error has-success').addClass('has-warning');
		        $(datePickerEnd).removeClass('has-warning has-error').addClass('has-success');
		    } else if (endDate == null && beginDate != null) {
		        $(datePickerBegin).removeClass('has-warning has-error').addClass('has-success');
		        $(datePickerEnd).removeClass('has-error has-success').addClass('has-warning');
		    } else if (beginDate.isSameOrBefore(endDate)) {
		        $(datePickerBegin).removeClass('has-warning has-error').addClass('has-success');
		        $(datePickerEnd).removeClass('has-warning has-error').addClass('has-success');
		    } else {
		        $(datePickerBegin).removeClass('has-warning has-success').addClass('has-error');
		        $(datePickerEnd).removeClass('has-warning has-success').addClass('has-error');
		    }
		    
		    var emailDate = getEmailDate();
		    if (emailDate == null && beginDate != null) {
		    	$(datePickerEmail).removeClass('has-error has-success').addClass('has-warning');
		    } else if (emailDate == null && beginDate == null) {
		    	$(datePickerEmail).removeClass('has-warning has-error has-success');
		    } else if (emailDate != null && beginDate != null && beginDate.isSameOrBefore(emailDate)) {
		    	$(datePickerEmail).removeClass('has-warning has-success').addClass('has-error');
		    } else {
		    	$(datePickerEmail).removeClass('has-warning has-error').addClass('has-success');
		    }
		}

		function setMinMaxDates() {
            if (getBeginDate() == null) {
                $(datePickerEnd).data("DateTimePicker").minDate(getCurrentDate());
                $(datePickerEmail).data("DateTimePicker").maxDate(false);
            } else {
                $(datePickerEnd).data("DateTimePicker").minDate(getBeginDate());
                $(datePickerEmail).data("DateTimePicker").maxDate(getBeginDate());
            }

            if (getEndDate() == null) {
                $(datePickerBegin).data("DateTimePicker").maxDate(false);
            } else {
                $(datePickerBegin).data("DateTimePicker").maxDate(getEndDate());
            }
		}

		function initDateTimePickers() {

		    $(datePickerBegin).datetimepicker({
		        locale: 'pl',
		        minDate: getCurrentDate(),
		        defaultDate: getCurrentDate().add(1,'d').hour(12).minute(0).second(0),
                useCurrent: false
		    });

            $(datePickerEnd).datetimepicker({
		        locale: 'pl',
		        minDate: getCurrentDate(),
		        defaultDate: getCurrentDate().add(1,'d').hour(12).minute(30).second(0),
                useCurrent: false
            });

            $(datePickerEmail).datetimepicker({
		        locale: 'pl',
		        minDate: getCurrentDate(),
		        defaultDate: getCurrentDate().add(1,'d').hour(11).minute(30).second(0),
                useCurrent: false
            });
            
            $(datePickerBegin).on("dp.change", function (e) {
                checkDatesAreValid();
                if (e.date != false) {
	                $(datePickerEnd).data("DateTimePicker").date(moment(e.date).add(10,'m'));
	                $(datePickerEmail).data("DateTimePicker").date(moment(e.date).subtract(10,'m'));
                }
            });

            $(datePickerEnd).on("dp.change", function (e) {
                checkDatesAreValid();
            });
            
            $(datePickerEmail).on("dp.change", function (e) {
                checkDatesAreValid();
            });
            
            checkDatesAreValid();
		}

		$(document).ready(function() {
		    initDateTimePickers();

			if ($(sendEmailCheckBox).is(":checked"))
		    	$(emailDateBlock).show();
		    else
	    		$(emailDateBlock).hide();

			$(sendEmailCheckBox).change(onSendEmailChange);
		});
	</script>

	<style>
		textarea[name=description] {
			width: 50%;
			max-width: 100%;
		}
		div[id^=datetimepicker] {
			width: 50%;
		}
	</style>

	<form action="{% url 'meetings:addsubmit' %}" method="post">
		{% csrf_token %}

		<label class="control-label" for="title">Tytuł spotkania</label>
		<input type="text" class="form-control" id="title" name="title" required autofocus />

		<br/>

		<label class="control-label" for="description">Dodatkowe notatki</label>
		<textarea class="form-control" id="description" name="description" rows="3"></textarea>

		<br/>

		<label class="control-label" for="begin">Data rozpoczęcia</label>
		<div class='input-group date' id='datetimepicker1'>
            <input type='text' class="form-control" id="begin" name="begin" required />
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>

		<br/>

		<label class="control-label" for="end">Data zakończenia</label>
		<div class='input-group date' id='datetimepicker2'>
            <input type='text' class="form-control" id="end" name="end" required />
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>

		<br/>

		<div class="checkbox">
			<label>
				<input type="checkbox" id="send_email" name="send_email">
				Wyślij email z przypomnieniem
			</label>
		</div>

		<br/>

		<div id="email_date_block" style="display:none">
            <label class="control-label" for="email_date">Data emaila</label>
            <div class='input-group date' id='datetimepicker3'>
                <input type='text' class="form-control" id="email_date" name="email_date" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>

		    <br/>
		</div>

		<button class="btn btn-success" type="submit">Zatwierdź spotkanie</button>

	</form>
{% endblock %}

templates/meetings/addsubmit.html
{% extends 'meetings/base.html' %}

{% block content-title %}Dodawanie spotkania{% endblock %}

{% block content %}
	{% if not error %}
		<p>Zaplanowano spotkanie!</p>
	
		<br/>
	
		<a class="btn btn-primary" href="{% url 'meetings:show' meeting.id %}">Podgląd spotkania</a>
		<a class="btn btn-info" href="{% url 'meetings:index' %}">Lista spotkań</a>
	{% else %}
	    <p>{{ error }}</p>
	
		<br/>
	
		<button class="btn btn-default" onclick="javascript:history.go(-1)">Powrót</button>
	{% endif %}
{% endblock %}

templates/meetings/base.html
{% extends 'base.html' %}

{% block title %}Organizer - Spotkania{% endblock %}

{% block content-title %}Spotkania{% endblock %}

templates/meetings/index.html
{% extends 'meetings/base.html' %}

{% block content-title %}Lista zaplanowanych spotkań{% endblock %}

{% block content %}
	<style>
		.meetingsList {
			margin: 0px;
		}
		.meetingsListItem {
			margin: 0px;
			padding: 5px 0px;
			font-family: Verdana;
			font-size: 18px;
		}
		.meetingTitle {
			color: blue;
		}
		.meetingTitle:hover {
			color: maroon;
		}
		.meetingTime {
			font-size: 14px;
		}
		.meetingRemove {
			margin: auto 10px;
		}
		.noMeetingsInfo {
			margin: 10px 20px;
			font-size: 20px;
		}
	</style>

	{% if meetings %}
		<ol class="meetingsList">
			{% for meeting in meetings %}
			<li class="meetingsListItem">
				<a class="meetingTitle" 
					href="{% url 'meetings:show' meeting.id %}" 
					data-toggle="tooltip" data-placement="bottom" 
					title="Podgląd spotkania">
					{{ meeting.title }}</a>
				<span class="meetingTime" 
					data-toggle="tooltip" data-placement="bottom" 
					title="Data rozpoczęcia spotkania">
					({{ meeting.begin | date }})</span>
				<a class="btn btn-danger btn-xs meetingRemove" 
					href="{% url 'meetings:remove' meeting.id %}">
					Usuń</a>
			</li>
			{% endfor %}
		</ol>
	{% else %}
		<p class="noMeetingsInfo">Brak zaplanowanych spotkań.</p>
	{% endif %}

	<br/>

	<a class="btn btn-success" href="{% url 'meetings:add' %}">Utwórz spotkanie</a>
{% endblock %}

templates/meetings/mail.html
<div style="font-family: Verdana;">
	<h2 style="font-family: Comic Sans MS; color: blue;">
		Przypomnienie o nadchodzącym spotkaniu!
	</h2>
	
	<p>
		<span style="font-weight: bold; color: brown;">
			Tytuł:
		</span>
		{{ meeting.title }}
	</p>
	
{% if meeting.description %}
	<p>
		<span style="font-weight: bold; color: brown;">
			Notatki:
		</span>
		{{ meeting.description | linebreaksbr }}
	</p>
{% endif %}
	
	<p>
		<span style="font-weight: bold; color: brown;">
			Data rozpoczęcia:
		</span>
		{{ meeting.begin | date }}
	</p>
	
	<p>
		<span style="font-weight: bold; color: brown;">
			Data zakończenia:
		</span>
		{{ meeting.end | date }}
	</p>
	
	<h2 style="font-family: Courier New; color: green;">
		Pozdrawiamy!
	</h2>
</div>

templates/meetings/remove.html
{% extends 'meetings/base.html' %}

{% block content-title %}Usuwanie spotkania{% endblock %}

{% block content %}
	{% if not error %}
		<p>Pomyślnie usunięto zaplanowane spotkanie!</p>
	
		<br/>
	
		<a class="btn btn-info" href="{% url 'meetings:index' %}">Lista spotkań</a>
	{% else %}
	    <p>{{ error }}</p>
	
		<br/>
	
		<button class="btn btn-default" onclick="javascript:history.go(-1)">Powrót</button>
	{% endif %}
{% endblock %}

templates/meetings/show.html
{% extends 'meetings/base.html' %}

{% block content-title %}Podgląd spotkania{% endblock %}

{% block content %}
	{% if not error %}
	    <style>
	        .meetingHeader {
				color: brown;
				font-weight: bold;
			}
			#meetingInfo p {
				margin: 20px 10px;
				font-family: Verdana;
				font-size: 16px;
			}
	    </style>
		
		<div id="meetingInfo">
		
	    <p>
	        <span class="meetingHeader">Tytuł spotkania:</span>
	        <span>{{ meeting.title }}</span>
	    </p>
	
		{% if meeting.description %}
	        <p>
	            <span class="meetingHeader">Notatki:</span>
	            <span>{{ meeting.description | linebreaksbr }}</span>
	        </p>
		{% endif %}
	
	    <p>
	        <span class="meetingHeader">Data rozpoczęcia:</span>
	        <span>{{ meeting.begin | date }}</span>
	    </p>
	
	    <p>
	        <span class="meetingHeader">Data zakończenia:</span>
	        <span>{{ meeting.end | date }}</span>
	    </p>
	
		{% if meeting.send_email %}
	        <p>
	            <span class="meetingHeader">Data emaila:</span>
	            <span>{{ meeting.email_date | date }}</span>
	        </p>
	
		    <br/>
	
	        <p>
                {% if meeting.email_was_send %}
                    <span>Email z przypomnieniem został już wysłany.</span>
                {% else %}
                    <span>Email nie został jeszcze wysłany.</span>
                {% endif %}
	        </p>
		{% endif %}
		
		</div>
	
		<br/>
	
		<a class="btn btn-danger" href="{% url 'meetings:remove' meeting.id %}">Usuń spotkanie</a>
		<a class="btn btn-info" href="{% url 'meetings:index' %}">Lista spotkań</a>
	{% else %}
	    <p>{{ error }}</p>
	
		<br/>
	
		<button class="btn btn-default" onclick="javascript:history.go(-1)">Powrót</button>
	{% endif %}
{% endblock %}