jobs/urls.py
from django.conf.urls import url

from jobs import views

app_name = "jobs"

urlpatterns = [
    url(r'^$', views.index, name='index'),
	url(r'^add/$', views.add, name='add'),
	url(r'^add/submit/$', views.addsubmit, name='addsubmit'),
	url(r'^show/(?P<job_id>[0-9]+)/$', views.show, name='show'),
    url(r'^remove/(?P<job_id>[0-9]+)/$', views.remove, name='remove')
]

organizer/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

from organizer import settings
from organizer import views

from organizer.tools import IsLinux

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^jobs/', include('jobs.urls')),
    url(r'^meetings/', include('meetings.urls')),
    url(r'^accounts/login/$', views.account_login, name='login'),
    url(r'^accounts/logged_in/$', views.account_logged_in, name='logged_in'),
    url(r'^accounts/logout/$', views.account_logout, name='logout'),
    url(r'^accounts/logged_out/$', views.account_logged_out, name='logged_out'),
    url(r'^accounts/create/$', views.account_create, name='create'),
    url(r'^accounts/created/$', views.account_created, name='created'),
    url(r'^admin/', admin.site.urls),
]

if not IsLinux():
    favicon_view = RedirectView.as_view(url=settings.STATIC_URL + 'favicon.ico')
    robots_view = RedirectView.as_view(url=settings.STATIC_URL + 'robots.txt')
    urlpatterns.append(url(r'^favicon\.ico$', favicon_view))
    urlpatterns.append(url(r'^robots\.txt$', robots_view))

jobs/models.py
from __future__ import unicode_literals

from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.dateformat import DateFormat
from django.utils.formats import get_format

@python_2_unicode_compatible
class Job(models.Model):
	user = models.ForeignKey(User)
	title = models.CharField(max_length=200)
	description = models.TextField(max_length=1000)
	date = models.DateTimeField()
	added = models.DateTimeField(default=timezone.now)
	send_email = models.BooleanField()
	email_date = models.DateTimeField()
	email_was_send = models.BooleanField()
	
	def __str__(self):
		fixed_date = timezone.make_naive(self.date)
		datestr = DateFormat(fixed_date).format(get_format('DATE_FORMAT'))
		return "%s [%s]" % (self.title, datestr)

jobs/views.py
#coding: utf-8

from django.shortcuts import render
from django.utils import timezone
from datetime import datetime, timedelta
from django.contrib.auth.decorators import login_required

from .models import Job
from organizer.tools import ErrorMessage

@login_required
def index(request):
	job_list = Job.objects.filter(user=request.user)
	context = { 'job_list': job_list }
	return render(request, 'jobs/index.html', context)

@login_required
def add(request):
	date_now = timezone.now()
	prefjobdate = date_now + timedelta(days=1)
	prefemaildate = prefjobdate - timedelta(hours=1)
	context = {
		'date_now': date_now,
		'prefjobdate': prefjobdate,
		'prefemaildate': prefemaildate
	}
	return render(request, 'jobs/add.html', context)

@login_required
def addsubmit(request):
	error = ErrorMessage()
	job = Job()
	
	date_now = timezone.now()

	post_title = request.POST.get("title", "")
	post_description = request.POST.get("description", "")
	post_date = request.POST.get("date", "")
	post_sendemail = request.POST.get("sendemail", "")
	post_emaildate = request.POST.get("emaildate", "")
	
	fixed_date = date_now
	fixed_email_date = date_now
	fixed_sendemail = (post_sendemail != "")
	
	if post_title == "":
		error.set("Musisz podać tytuł zadania!")
	#elif post_description == "":
	#	error.set("Musisz podać treść zadania!")
	elif post_date == "":
		error.set("Musisz podać datę zadania!")
	elif fixed_sendemail and post_emaildate == "":
		error.set("Musisz podać datę emaila!")

	if error.good():
		try:
			fixed_date = datetime.strptime(post_date, "%Y-%m-%dT%H:%M")
			fixed_date = timezone.make_aware(fixed_date)
		except:
			error.set("Data zadania jest nieprawidłowa!")
		else:
			if fixed_date <= date_now:
				error.set("Data zadania musi wyprzedzać aktualny czas!")
	
	if fixed_sendemail and error.good():
		try:
			fixed_email_date = datetime.strptime(post_emaildate, "%Y-%m-%dT%H:%M")
			fixed_email_date = timezone.make_aware(fixed_email_date)
		except:
			error.set("Data emaila jest nieprawidłowa!")
		else:
			if fixed_email_date <= date_now:
				error.set("Data emaila musi wyprzedzać aktualny czas!")
			elif fixed_email_date > fixed_date:
				error.set("Data emaila musi poprzedzać datę zadania!")
	
	if error.good():
		job.user = request.user
		job.title = post_title
		job.description = post_description
		job.date = fixed_date
		job.send_email = fixed_sendemail
		job.email_date = fixed_email_date
		job.email_was_send = False
		job.save()
		
	context = {
		'date_now': date_now,
		'no_error': error.good(),
		'error_message': error.message
	}
	
	if error.good():
		context.update({
			'id': job.id,
			'jobdate': job.date,
			'title': job.title,
			'description': job.description,
			'sendemail': job.send_email,
			'emailwassend': job.email_was_send,
			'emaildate': job.email_date
		})
	
	return render(request, 'jobs/addsubmit.html', context)

@login_required
def show(request, job_id):
	error = ErrorMessage()
	
	try:
		job = Job.objects.get(id=job_id)
	except:
		error.set("Zadanie o podanym ID nie istnieje!")
	else:
		if job.user != request.user:
			error.set("Nie jesteś właścicielem tego zadania!")
	
	context = {
		'no_error': error.good(),
		'error_message': error.message
	}
	
	if error.good():
		context.update({
			'id': job.id,
			'jobdate': job.date,
			'title': job.title,
			'description': job.description,
			'sendemail': job.send_email,
			'emailwassend': job.email_was_send,
			'emaildate': job.email_date
		})
	
	return render(request, 'jobs/show.html', context)

@login_required
def remove(request, job_id):
	error = ErrorMessage()
	
	try:
		job = Job.objects.get(id=job_id)
	except:
		error.set("Zadanie o podanym ID nie istnieje!")
	else:
		if job.user != request.user:
			error.set("Nie jesteś właścicielem tego zadania!")
	
	if error.good():
		job.delete()
	
	context = {
		'no_error': error.good(),
		'error_message': error.message
	}
	
	return render(request, 'jobs/remove.html', context)

templates/jobs/add.html
{% extends 'jobs/base.html' %}

{% block content-title %}Tworzenie zadania{% endblock %}

{% block content %}
	<script>
		function onSendEmailChange() {
			$('#emaildateblock').stop();
		    if ($("input[name=sendemail]").is(":checked"))
		    	$('#emaildateblock').fadeIn();
		    else
	    		$('#emaildateblock').fadeOut();
		}

		$(document).ready(function() {
			onSendEmailChange();
			$("input[name=sendemail]").change(onSendEmailChange);
		});
	</script>
	
	<style>
		textarea[name=description] {
			width: 50%;
			max-width: 100%;
		}
		input[type=datetime-local] {
			width: 50%;
		}
	</style>

	<form action="{% url 'jobs:addsubmit' %}" method="post">
		{% csrf_token %}

		<label class="control-label" for="title">Tytuł zadania</label>
		<input type="text" class="form-control" name="title" required autofocus />

		<br/>
		
		<label class="control-label" for="description">Opis zadania</label>
		<textarea class="form-control" name="description" rows="3"></textarea>

		<br/>
		
		<label class="control-label" for="date">Data zadania</label>
		<input type="datetime-local" class="form-control" name="date" />

		<br/>
		
		<div class="checkbox">
			<label>
				<input type="checkbox" name="sendemail">
				Wysłać email z przypomnieniem?
			</label>
		</div>

		<br/>
		
		<div id="emaildateblock" style="display:none">
			<label class="control-label" for="emaildate">Data emaila<br/></label>
			<input type="datetime-local" class="form-control" name="emaildate" />
		</div>

		<br/>
		
		<button class="btn btn-success" type="submit">Dodaj zadanie</button>
	</form>
{% endblock %}

templates/jobs/addsubmit.html
{% extends 'jobs/base.html' %}

{% block content-title %}Dodawanie zadania{% endblock %}

{% block content %}
	{% if no_error %}
		<p>Dodano zadanie!</p>
		
		<br/>
		
		<a class="btn btn-primary" href="{% url 'jobs:show' id %}">Podgląd zadania</a>
		<a class="btn btn-info" href="{% url 'jobs:index' %}">Lista zadań</a>
	{% else %}
		<p>{{ error_message }}</p>
		
		<br/>
		
		<button class="btn btn-default" onclick="javascript:history.go(-1)">Powrót</button>
	{% endif %}
{% endblock %}

templates/jobs/base.html
{% extends 'base.html' %}

{% block style %}<link rel="stylesheet" href="{% static 'css/jobs.css' %}">{% endblock %}

{% block title %}Organizer - Zadania{% endblock %}

{% block content-title %}Zadania{% endblock %}

templates/jobs/index.html
{% extends 'jobs/base.html' %}

{% block content-title %}Lista zadań{% endblock %}

{% block content %}
	{% if job_list %}
		<ul class="jobList">
			{% for job in job_list %}
			<li class="jobListItem">
				<a class="jobTitleLink" href="{% url 'jobs:show' job.id %}">{{ job.title }}</a>
				<a class="deleteLink" href="{% url 'jobs:remove' job.id %}">Usuń</a>
			</li>
			{% endfor %}
		</ul>
	{% else %}
		<p class="noJobsInfo">Brak aktywnych zadań.</p>
	{% endif %}
	
	<br/>

	<a class="btn btn-success" href="{% url 'jobs:add' %}">Utwórz zadanie</a>
{% endblock %}

templates/jobs/mail.html
<div style="font-family: Verdana;">
	<h2 style="font-family: Comic Sans MS; color: blue;">
		Przypomnienie o nadchodzącym zadaniu!
	</h2>
	
	<p>
		<span style="font-weight: bold; color: brown;">
			Tytuł zadania:
		</span>
		{{ job.title }}
	</p>
	
{% if job.description %}
	<p>
		<span style="font-weight: bold; color: brown;">
			Opis zadania:
		</span>
		{{ job.description | linebreaksbr }}
	</p>
{% endif %}
	
	<p>
		<span style="font-weight: bold; color: brown;">
			Data zadania:
		</span>
		{{ job.date | date }}
	</p>
	
	<h2 style="font-family: Courier New; color: green;">
		Pozdrawiamy!
	</h2>
</div>

templates/jobs/remove.html
{% extends 'jobs/base.html' %}

{% block content-title %}Usuwanie zadania{% endblock %}

{% block content %}
	{% if no_error %}
		<p>Pomyślnie usunięto zadanie!</p>

		<br/>
		
		<a class="btn btn-info" href="{% url 'jobs:index' %}">Lista zadań</a>
	{% else %}
		<p>{{ error_message }}</p>
		
		<br/>
		
		<button class="btn btn-default" onclick="javascript:history.go(-1)">Powrót</button>
	{% endif %}
{% endblock %}

templates/jobs/show.html
{% extends 'jobs/base.html' %}

{% block content-title %}Podgląd zadania{% endblock %}

{% block content %}
	<style>
		.job_header {
			color: brown;
			font-family: Verdana;
			font-weight: bold;
		}
	</style>

	{% if no_error %}
		<span id="job_title_header" class="job_header">Tytuł:</span>
		<span id="job_title">{{ title }}</span>
		
		<br/><br/>
		
		{% if description %}
			<span id="job_description_header" class="job_header">Opis:</span>
			<span id="job_description">{{ description | linebreaksbr }}</span>
	
			<br/><br/>
		{% endif %}
		
		<span id="job_date_header" class="job_header">Data zadania:</span>
		<span id="job_date">{{ jobdate | date }}</span>
	
		<br/> <br/>
		
		{% if sendemail %}
			<span id="job_emaildate_header" class="job_header">Data emaila:</span>
			<span id="job_emaildate">{{ emaildate | date }}</span>
	
			<br/><br/>
			
			{% if emailwassend %}
				<span id="job_emailwassend">Email z przypomnieniem został już wysłany.</span>
			{% else %}
				<span id="job_emailwassend">Email nie został jeszcze wysłany.</span>
			{% endif %}
	
			<br/><br/>
		{% endif %}
		
		<a class="btn btn-danger" href="{% url 'jobs:remove' id %}">Usuń zadanie</a>
		<a class="btn btn-info" href="{% url 'jobs:index' %}">Lista zadań</a>
	{% else %}
		<p>{{ error_message }}</p>
		
		<br/>
		
		<button class="btn btn-default" onclick="javascript:history.go(-1)">Powrót</button>
	{% endif %}
{% endblock %}